### ISSUE TITLE
希望读取剪贴板内容后做一下trim

### ISSUE THREAD

**Issue by CallMeNP** [kandu/goPage#1]
从excel(wps)单元格中复制的内容，尾部带有换行符，会识别为错误的文件名从而打开词典失败。
希望可以trim一下，移除首尾空白字符。

我在Ubuntu环境下工作，这个软件让我非常受益。由于没有打包经验，先提个issue。

**Comment by kandu** [comment]
测试了一下 wps 2019 linux 版。

操作1: 点选单元格 -> 复制。
结果: 前后都附加了额外数据，复制的内容为:\n单元格内容\r

操作2: 双击单元格 -> 复制。
结果: 复制的内容为即单元格内容，符合预期

若要让 goPage 对 操作1 进行兼容，则需进行一些改造。
因为 goPage 无法从剪贴板判断数据来源，若直接对内容进行修剪，容易造成其他软件或文件名的不兼容。
所以我设想的解决办法如下：

新增选项，wps/excel 兼容模式。点选后开启，遇到剪贴板内容前后都有换行的情况就进行修剪。若不开启兼容模式，则不修剪。这种解决办法你觉得如何？

另外，就我个人来说，操作2 与 操作1 的操作量类似。在 操作2 方式可行的情况下，增加软件复杂度似乎没有太多必要。
但以上仅是我个人使用感受，还是得听听更多的反馈意见，来决定是否进行改进。

**Comment by CallMeNP** [comment]
新增选项的话确实有些不必要了。

操作2 还是觉得麻烦些，后来发现 腾讯文档 等在线表格不会附加内容，使用顺畅。也算一种方案，写在这供大家参考吧。

**Comment by kandu** [comment]
最近测试了一下 libreoffice, wps 等表单软件，发现不同软件的表现各不相同。有前置空行，有后置的，有前后置的。

> 新增选项的话确实有些不必要了。

既然这是一个普遍存在的问题，那么新增一个专门的选项还是应该的。

**Comment by kandu** [comment]
resolved in https://github.com/kandu/goPage/commit/34d3b5ead2bfb6f6a629721e6fb9f564fe99ea31

**Comment by kandu** [comment]
![image](https://user-images.githubusercontent.com/357626/182615689-d398dc20-9545-4b7e-a74a-a7b92c38467e.png)

高亮选框即为新增选项。
