### ISSUE TITLE
希望在匹配pdf软件名的时候忽略大小写。

### ISSUE THREAD

**Issue by CallMeNP** [kandu/goPage#2]
在 Ubuntu(20.04) 下，PDF阅读工具 evince 的 desktop 文件为：/usr/share/applications/org.gnome.Evince.desktop

其中"Evince"为首字母大写。这会导致匹配失败，认为没有evince。因为 kandu/gopage 根据 /etc/goPage/reader.cfg 中的配置做匹配，而没有忽略大小写。

所以目前我安装gopage后，需要：
1，需要修改 /usr/share/applications/default.list 中 application/pdf 的值，增加 evince（小写）在前面。
2，或者复制 org.gnome.Evince.desktop 为全小写的文件名。

希望可以在匹配字符串之前，做一下大小写转换。或匹配是忽略大小写。

**Comment by kandu** [comment]
fixed in https://github.com/kandu/goPage/commit/991b7ded5feed04001ee9ba58f4784bb1f792103
